---
version: "1"
conflictLabel: "needs-rebase"
rules:
  - base: main
    upstream: opendatahub-io:main
    mergeMethod: none
  - base: release-2023a
    upstream: opendatahub-io:2023a
    mergeMethod: none
  - base: release-2023b
    upstream: opendatahub-io:2023b
    mergeMethod: none
  - base: release-2024a
    upstream: opendatahub-io:2024a
    mergeMethod: none
