[tool.poetry]
name = "notebooks"
version = "2024.1"
authors = []
description = "Open Data Hub / OpenShift AI Notebook / Workbench images, and tests for the same in Python."
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
allure-pytest = "^2.13.5"
pytest-subtests = "^0.12.1"
pyfakefs = "^5.7.2"
testcontainers = "^4.9.0"
docker = "^7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
